# PInstall Configuration File
# This file defines supported applications and their download patterns

applications:
  go:
    name: "Go Programming Language"
    description: "Open source programming language that makes it easy to build simple, reliable, and efficient software"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64", "x86"]
    download_patterns:
      linux:
        x64: "https://golang.org/dl/go{version}.linux-amd64.tar.gz"
        arm64: "https://golang.org/dl/go{version}.linux-arm64.tar.gz"
        x86: "https://golang.org/dl/go{version}.linux-386.tar.gz"
      mac:
        x64: "https://golang.org/dl/go{version}.darwin-amd64.tar.gz"
        arm64: "https://golang.org/dl/go{version}.darwin-arm64.tar.gz"
      win:
        x64: "https://golang.org/dl/go{version}.windows-amd64.zip"
        arm64: "https://golang.org/dl/go{version}.windows-arm64.zip"
        x86: "https://golang.org/dl/go{version}.windows-386.zip"
    env_vars:
      GOROOT: "{install_path}"
      GOPATH: "{home}/go"
      PATH: "{install_path}/bin:{home}/go/bin"
    
  node:
    name: "Node.js"
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64", "x86"]
    download_patterns:
      linux:
        x64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-x64.tar.xz"
        arm64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-arm64.tar.xz"
        x86: "https://nodejs.org/dist/v{version}/node-v{version}-linux-x86.tar.xz"
      mac:
        x64: "https://nodejs.org/dist/v{version}/node-v{version}-darwin-x64.tar.gz"
        arm64: "https://nodejs.org/dist/v{version}/node-v{version}-darwin-arm64.tar.gz"
      win:
        x64: "https://nodejs.org/dist/v{version}/node-v{version}-win-x64.zip"
        arm64: "https://nodejs.org/dist/v{version}/node-v{version}-win-arm64.zip"
        x86: "https://nodejs.org/dist/v{version}/node-v{version}-win-x86.zip"
    env_vars:
      NODE_HOME: "{install_path}"
      PATH: "{install_path}/bin"
      
  python:
    name: "Python"
    description: "High-level programming language for general-purpose programming"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64", "x86"]
    package_manager_install: true
    download_patterns:
      win:
        x64: "https://www.python.org/ftp/python/{version}/python-{version}-amd64.exe"
        x86: "https://www.python.org/ftp/python/{version}/python-{version}.exe"
    env_vars:
      PYTHON_HOME: "{install_path}"
      PATH: "{install_path}:{install_path}/Scripts"
      
  docker:
    name: "Docker"
    description: "Platform for developing, shipping, and running applications in containers"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64"]
    package_manager_install: true
    download_patterns:
      win:
        x64: "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
      mac:
        x64: "https://desktop.docker.com/mac/main/amd64/Docker.dmg"
        arm64: "https://desktop.docker.com/mac/main/arm64/Docker.dmg"
        
  git:
    name: "Git"
    description: "Distributed version control system"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64", "x86"]
    package_manager_install: true
    download_patterns:
      win:
        x64: "https://github.com/git-for-windows/git/releases/latest/download/Git-{version}-64-bit.exe"
        x86: "https://github.com/git-for-windows/git/releases/latest/download/Git-{version}-32-bit.exe"
        
  kubectl:
    name: "Kubernetes kubectl"
    description: "Command-line tool for controlling Kubernetes clusters"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64"]
    download_patterns:
      linux:
        x64: "https://dl.k8s.io/release/v{version}/bin/linux/amd64/kubectl"
        arm64: "https://dl.k8s.io/release/v{version}/bin/linux/arm64/kubectl"
      mac:
        x64: "https://dl.k8s.io/release/v{version}/bin/darwin/amd64/kubectl"
        arm64: "https://dl.k8s.io/release/v{version}/bin/darwin/arm64/kubectl"
      win:
        x64: "https://dl.k8s.io/release/v{version}/bin/windows/amd64/kubectl.exe"
        
  terraform:
    name: "Terraform"
    description: "Infrastructure as Code tool for building, changing, and versioning infrastructure"
    supported_os: ["linux", "mac", "win"]
    supported_arch: ["x64", "arm64"]
    download_patterns:
      linux:
        x64: "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_linux_amd64.zip"
        arm64: "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_linux_arm64.zip"
      mac:
        x64: "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_darwin_amd64.zip"
        arm64: "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_darwin_arm64.zip"
      win:
        x64: "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_windows_amd64.zip"
        
# Popular versions for quick reference
popular_versions:
  go:
    - "1.24.4"
    - "1.23.8"
    - "1.22.11"
  node:
    - "20.10.0"
    - "18.19.0"
    - "16.20.2"
  python:
    - "3.12.0"
    - "3.11.7"
    - "3.10.13"
  kubectl:
    - "1.29.0"
    - "1.28.5"
    - "1.27.9"
  terraform:
    - "1.6.6"
    - "1.5.7"
    - "1.4.7"
